// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice =
  | ImageHeroSlice
  | WhyChooseUsSlice
  | TestimonialsSectionSlice
  | TeamIndexSlice
  | VisionAndMissionSlice
  | BlogIndexSlice
  | ContactSectionSlice
  | ContentWithButtonsSlice
  | ServicesIndexSlice
  | FaqSliceSlice
  | HeadingContentSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Featured Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Author field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Excerpt field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type HomepageDocumentDataSlicesSlice =
  | ImageBackgroundSlice
  | CallToActionSlice
  | FeatureImageCarouselSlice
  | TeamIndexSlice
  | ContactSectionSlice
  | BlogIndexSlice
  | ContentWithButtonsSlice
  | ServicesIndexSlice
  | FaqSliceSlice
  | WhyChooseUsSlice
  | TestimonialsSectionSlice
  | ImageHeroSlice
  | VisionAndMissionSlice
  | HeadingContentSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ImageBackgroundSlice
  | CallToActionSlice
  | FeatureImageCarouselSlice
  | ContentWithButtonsSlice
  | ContactSectionSlice
  | TeamIndexSlice
  | ServicesIndexSlice
  | BlogIndexSlice
  | FaqSliceSlice
  | WhyChooseUsSlice
  | TestimonialsSectionSlice
  | ImageHeroSlice
  | VisionAndMissionSlice
  | HeadingContentSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServiceDocumentDataSlicesSlice =
  | ImageHeroSlice
  | TestimonialsSectionSlice
  | TeamIndexSlice
  | VisionAndMissionSlice
  | WhyChooseUsSlice
  | ContactSectionSlice
  | BlogIndexSlice
  | HeadingContentSlice
  | FaqSliceSlice
  | ContentWithButtonsSlice
  | ServicesIndexSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Service Name field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.service_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_name: prismic.KeyTextField;

  /**
   * Featured Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Service Excerpt field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.service_excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_excerpt: prismic.KeyTextField;

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | HomepageDocument
  | PageDocument
  | ServiceDocument;

/**
 * Primary content in *BlogIndex → Default → Primary*
 */
export interface BlogIndexSliceDefaultPrimary {
  /**
   * Heading field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for BlogIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogIndex*
 */
type BlogIndexSliceVariation = BlogIndexSliceDefault;

/**
 * BlogIndex Shared Slice
 *
 * - **API ID**: `blog_index`
 * - **Description**: BlogIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogIndexSlice = prismic.SharedSlice<
  "blog_index",
  BlogIndexSliceVariation
>;

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *ContentWithButtons → Default → Primary*
 */
export interface ContentWithButtonsSliceDefaultPrimary {
  /**
   * Heading field in *ContentWithButtons → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_buttons.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ContentWithButtons → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_buttons.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for ContentWithButtons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithButtonsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentWithButtonsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentWithButtons*
 */
type ContentWithButtonsSliceVariation = ContentWithButtonsSliceDefault;

/**
 * ContentWithButtons Shared Slice
 *
 * - **API ID**: `content_with_buttons`
 * - **Description**: ContentWithButtons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithButtonsSlice = prismic.SharedSlice<
  "content_with_buttons",
  ContentWithButtonsSliceVariation
>;

/**
 * Item in *FaqSlice → Default → Primary → Questions*
 */
export interface FaqSliceSliceDefaultPrimaryQuestionsItem {
  /**
   * question field in *FaqSlice → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqSlice → Default → Primary → Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqSlice → Default → Primary*
 */
export interface FaqSliceSliceDefaultPrimary {
  /**
   * Heading field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Questions field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<
    Simplify<FaqSliceSliceDefaultPrimaryQuestionsItem>
  >;
}

/**
 * Default variation for FaqSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqSlice*
 */
type FaqSliceSliceVariation = FaqSliceSliceDefault;

/**
 * FaqSlice Shared Slice
 *
 * - **API ID**: `faq_slice`
 * - **Description**: FaqSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceSlice = prismic.SharedSlice<
  "faq_slice",
  FaqSliceSliceVariation
>;

/**
 * Default variation for FeatureImageCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureImageCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FeatureImageCarousel*
 */
type FeatureImageCarouselSliceVariation = FeatureImageCarouselSliceDefault;

/**
 * FeatureImageCarousel Shared Slice
 *
 * - **API ID**: `feature_image_carousel`
 * - **Description**: FeatureImageCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureImageCarouselSlice = prismic.SharedSlice<
  "feature_image_carousel",
  FeatureImageCarouselSliceVariation
>;

/**
 * Primary content in *HeadingContent → Default → Primary*
 */
export interface HeadingContentSliceDefaultPrimary {
  /**
   * Featured Content field in *HeadingContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_content.default.primary.featured_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_content: prismic.RichTextField;
}

/**
 * Default variation for HeadingContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeadingContent → Content With Muted Background → Primary*
 */
export interface HeadingContentSliceContentWithMutedBackgroundPrimary {
  /**
   * Featured Content field in *HeadingContent → Content With Muted Background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_content.contentWithMutedBackground.primary.featured_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_content: prismic.RichTextField;
}

/**
 * Content With Muted Background variation for HeadingContent Slice
 *
 * - **API ID**: `contentWithMutedBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingContentSliceContentWithMutedBackground =
  prismic.SharedSliceVariation<
    "contentWithMutedBackground",
    Simplify<HeadingContentSliceContentWithMutedBackgroundPrimary>,
    never
  >;

/**
 * Slice variation for *HeadingContent*
 */
type HeadingContentSliceVariation =
  | HeadingContentSliceDefault
  | HeadingContentSliceContentWithMutedBackground;

/**
 * HeadingContent Shared Slice
 *
 * - **API ID**: `heading_content`
 * - **Description**: HeadingContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingContentSlice = prismic.SharedSlice<
  "heading_content",
  HeadingContentSliceVariation
>;

/**
 * Primary content in *ImageBackground → Default → Primary*
 */
export interface ImageBackgroundSliceDefaultPrimary {
  /**
   * Heading field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_background.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_background.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Background Image field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_background.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageBackground*
 */
type ImageBackgroundSliceVariation = ImageBackgroundSliceDefault;

/**
 * ImageBackground Shared Slice
 *
 * - **API ID**: `image_background`
 * - **Description**: ImageBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBackgroundSlice = prismic.SharedSlice<
  "image_background",
  ImageBackgroundSliceVariation
>;

/**
 * Primary content in *ImageHero → Default → Primary*
 */
export interface ImageHeroSliceDefaultPrimary {
  /**
   * Background Image field in *ImageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ImageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for ImageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageHero → ImageBackgroundWithMargin → Primary*
 */
export interface ImageHeroSliceImageBackgroundWithMarginPrimary {
  /**
   * Background Image field in *ImageHero → ImageBackgroundWithMargin → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_hero.imageBackgroundWithMargin.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageHero → ImageBackgroundWithMargin → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_hero.imageBackgroundWithMargin.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ImageHero → ImageBackgroundWithMargin → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_hero.imageBackgroundWithMargin.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * ImageBackgroundWithMargin variation for ImageHero Slice
 *
 * - **API ID**: `imageBackgroundWithMargin`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageHeroSliceImageBackgroundWithMargin =
  prismic.SharedSliceVariation<
    "imageBackgroundWithMargin",
    Simplify<ImageHeroSliceImageBackgroundWithMarginPrimary>,
    never
  >;

/**
 * Slice variation for *ImageHero*
 */
type ImageHeroSliceVariation =
  | ImageHeroSliceDefault
  | ImageHeroSliceImageBackgroundWithMargin;

/**
 * ImageHero Shared Slice
 *
 * - **API ID**: `image_hero`
 * - **Description**: ImageHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageHeroSlice = prismic.SharedSlice<
  "image_hero",
  ImageHeroSliceVariation
>;

/**
 * Primary content in *ServicesIndex → Default → Primary*
 */
export interface ServicesIndexSliceDefaultPrimary {
  /**
   * Heading field in *ServicesIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_index.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for ServicesIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesIndex*
 */
type ServicesIndexSliceVariation = ServicesIndexSliceDefault;

/**
 * ServicesIndex Shared Slice
 *
 * - **API ID**: `services_index`
 * - **Description**: ServicesIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesIndexSlice = prismic.SharedSlice<
  "services_index",
  ServicesIndexSliceVariation
>;

/**
 * Item in *TeamIndex → Default → Primary → Members*
 */
export interface TeamIndexSliceDefaultPrimaryMembersItem {
  /**
   * Member Name field in *TeamIndex → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.members[].member_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_name: prismic.KeyTextField;

  /**
   * Member Designation field in *TeamIndex → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.members[].member_designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_designation: prismic.KeyTextField;

  /**
   * Member Image field in *TeamIndex → Default → Primary → Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.members[].member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;

  /**
   * Member Description field in *TeamIndex → Default → Primary → Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.members[].member_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_description: prismic.RichTextField;
}

/**
 * Primary content in *TeamIndex → Default → Primary*
 */
export interface TeamIndexSliceDefaultPrimary {
  /**
   * Heading field in *TeamIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tag field in *TeamIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Tagline field in *TeamIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Members field in *TeamIndex → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  members: prismic.GroupField<
    Simplify<TeamIndexSliceDefaultPrimaryMembersItem>
  >;
}

/**
 * Default variation for TeamIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamIndex*
 */
type TeamIndexSliceVariation = TeamIndexSliceDefault;

/**
 * TeamIndex Shared Slice
 *
 * - **API ID**: `team_index`
 * - **Description**: TeamIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamIndexSlice = prismic.SharedSlice<
  "team_index",
  TeamIndexSliceVariation
>;

/**
 * Primary content in *TestimonialsSection → Default → Primary*
 */
export interface TestimonialsSectionSliceDefaultPrimary {
  /**
   * Heading field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Author field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Default variation for TestimonialsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialsSection*
 */
type TestimonialsSectionSliceVariation = TestimonialsSectionSliceDefault;

/**
 * TestimonialsSection Shared Slice
 *
 * - **API ID**: `testimonials_section`
 * - **Description**: TestimonialsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSectionSlice = prismic.SharedSlice<
  "testimonials_section",
  TestimonialsSectionSliceVariation
>;

/**
 * Primary content in *VisionAndMission → Default → Primary*
 */
export interface VisionAndMissionSliceDefaultPrimary {
  /**
   * Vision Heading field in *VisionAndMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_and_mission.default.primary.vision_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vision_heading: prismic.KeyTextField;

  /**
   * Vision Text field in *VisionAndMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_and_mission.default.primary.vision_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vision_text: prismic.KeyTextField;

  /**
   * Mission Heading field in *VisionAndMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_and_mission.default.primary.mission_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mission_heading: prismic.KeyTextField;

  /**
   * Mission Text field in *VisionAndMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_and_mission.default.primary.mission_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mission_text: prismic.KeyTextField;
}

/**
 * Default variation for VisionAndMission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionAndMissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionAndMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisionAndMission*
 */
type VisionAndMissionSliceVariation = VisionAndMissionSliceDefault;

/**
 * VisionAndMission Shared Slice
 *
 * - **API ID**: `vision_and_mission`
 * - **Description**: VisionAndMission
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionAndMissionSlice = prismic.SharedSlice<
  "vision_and_mission",
  VisionAndMissionSliceVariation
>;

/**
 * Item in *WhyChooseUs → Default → Primary → Reasons*
 */
export interface WhyChooseUsSliceDefaultPrimaryReasonsItem {
  /**
   * Reason Name field in *WhyChooseUs → Default → Primary → Reasons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.reasons[].reason_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reason_name: prismic.KeyTextField;

  /**
   * Reason Explanation field in *WhyChooseUs → Default → Primary → Reasons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.reasons[].reason_explanation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reason_explanation: prismic.KeyTextField;

  /**
   * Reason Image field in *WhyChooseUs → Default → Primary → Reasons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.reasons[].reason_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  reason_image: prismic.ImageField<never>;
}

/**
 * Primary content in *WhyChooseUs → Default → Primary*
 */
export interface WhyChooseUsSliceDefaultPrimary {
  /**
   * Heading field in *WhyChooseUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Reasons field in *WhyChooseUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.reasons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reasons: prismic.GroupField<
    Simplify<WhyChooseUsSliceDefaultPrimaryReasonsItem>
  >;
}

/**
 * Default variation for WhyChooseUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyChooseUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyChooseUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyChooseUs*
 */
type WhyChooseUsSliceVariation = WhyChooseUsSliceDefault;

/**
 * WhyChooseUs Shared Slice
 *
 * - **API ID**: `why_choose_us`
 * - **Description**: WhyChooseUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyChooseUsSlice = prismic.SharedSlice<
  "why_choose_us",
  WhyChooseUsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogIndexSlice,
      BlogIndexSliceDefaultPrimary,
      BlogIndexSliceVariation,
      BlogIndexSliceDefault,
      CallToActionSlice,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      ContentWithButtonsSlice,
      ContentWithButtonsSliceDefaultPrimary,
      ContentWithButtonsSliceVariation,
      ContentWithButtonsSliceDefault,
      FaqSliceSlice,
      FaqSliceSliceDefaultPrimaryQuestionsItem,
      FaqSliceSliceDefaultPrimary,
      FaqSliceSliceVariation,
      FaqSliceSliceDefault,
      FeatureImageCarouselSlice,
      FeatureImageCarouselSliceVariation,
      FeatureImageCarouselSliceDefault,
      HeadingContentSlice,
      HeadingContentSliceDefaultPrimary,
      HeadingContentSliceContentWithMutedBackgroundPrimary,
      HeadingContentSliceVariation,
      HeadingContentSliceDefault,
      HeadingContentSliceContentWithMutedBackground,
      ImageBackgroundSlice,
      ImageBackgroundSliceDefaultPrimary,
      ImageBackgroundSliceVariation,
      ImageBackgroundSliceDefault,
      ImageHeroSlice,
      ImageHeroSliceDefaultPrimary,
      ImageHeroSliceImageBackgroundWithMarginPrimary,
      ImageHeroSliceVariation,
      ImageHeroSliceDefault,
      ImageHeroSliceImageBackgroundWithMargin,
      ServicesIndexSlice,
      ServicesIndexSliceDefaultPrimary,
      ServicesIndexSliceVariation,
      ServicesIndexSliceDefault,
      TeamIndexSlice,
      TeamIndexSliceDefaultPrimaryMembersItem,
      TeamIndexSliceDefaultPrimary,
      TeamIndexSliceVariation,
      TeamIndexSliceDefault,
      TestimonialsSectionSlice,
      TestimonialsSectionSliceDefaultPrimary,
      TestimonialsSectionSliceVariation,
      TestimonialsSectionSliceDefault,
      VisionAndMissionSlice,
      VisionAndMissionSliceDefaultPrimary,
      VisionAndMissionSliceVariation,
      VisionAndMissionSliceDefault,
      WhyChooseUsSlice,
      WhyChooseUsSliceDefaultPrimaryReasonsItem,
      WhyChooseUsSliceDefaultPrimary,
      WhyChooseUsSliceVariation,
      WhyChooseUsSliceDefault,
    };
  }
}
